import "./globals.jsx";
import "../styles/tokens.css";
import "../styles/site.css";

import "./icons.jsx";
import "./util.jsx";
import "./Nav.jsx";
import "./Hero.jsx";
import "./SpecStrip.jsx";
import "./Features.jsx";
import "./AIFlow.jsx";
import "./Philosophy.jsx";
import "./EditorPreview.jsx";
import "./CodeSample.jsx";
import "./Download.jsx";
import "./Footer.jsx";
import "./tweaks-panel.jsx";
import "./Tweaks.jsx";
import "./App.jsx";
